version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'example'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ${PWD}/mysqlData:/var/lib/mysql
      - ${PWD}/:/etc/mysql/conf.d
